"use client";
import { useEffect, useState } from "react";

const experiences=[
 {place:"The Intelligence Tower",role:"Software Developer, Data & Systems",org:"Stony Brook University · Dec 2025–May 2026",text:"Built a modular multi-stage GPT-4/Claude pipeline to classify, summarize and triage 50,000+ unstructured IT service records. Traced a silent production data bug to reused serial numbers and implemented date-aware entity matching across 442 log files.",metrics:["50,000+ records","442 log files","0 parse failures"]},
 {place:"The Observatory",role:"AI/ML Engineer",org:"KPMG US · Aug–Dec 2023",text:"Built Python ETL over 1M+ U.S. Census 2020 records on AWS and developed regression, ensemble and neural-network models for workforce-equity analysis.",metrics:["1M+ records","up to 15% wage gaps","+20% decision support"]},
 {place:"The Technology Village",role:"Lead Student Technician",org:"Stony Brook University · Sep 2022–Dec 2025",text:"Supported students, faculty and staff across campus while turning operational knowledge into clearer workflows and training.",metrics:["500+ people","10+ buildings","99% satisfaction","50+ technicians"]}
];
const projects=[
 {title:"ScaleForge",sub:"Interactive System Design Learning Platform",text:"A full-stack JavaScript learning world for distributed systems: live incident simulation, tracing across CDNs, load balancers, caches and microservices, Three.js request routing, and an offline rule-based AI mentor.",demo:"https://scaleforge-83v.pages.dev/",github:"https://github.com/Tshrestha-1114/Scaleforge"},
 {title:"Edge Feedback Analytics",sub:"Cloudflare Ticket Aggregator",text:"A layered serverless analytics platform using Workers, D1 and KV. The integration schema supports GitHub, JIRA, Slack and Discord webhook sources and is currently exercised against seeded data.",demo:"https://sweet-morning-dc78.shresthapmcloudflare.workers.dev/",github:"https://github.com/Tshrestha-1114/cloudflare-tickets-aggregator-and-analyzer"},
 {title:"Company Brain",sub:"Organizational Intelligence · Currently Building",text:"A secure organizational-intelligence platform designed to connect company knowledge across people, projects, decisions, customers, events and outcomes, so authorized users can ask evidence-backed questions about why things happened.",status:"IN DEVELOPMENT"},
 {title:"AI Diet",sub:"Business Improvement Layer",text:"Built as the improvement layer above organizational intelligence: identify inefficiencies, bottlenecks, recurring problems and opportunities, then turn those patterns into recommendations for improving the business.",demo:"https://quorum-demo-7yk.pages.dev/"}
];

export function KingdomPortfolio(){
 const [section,setSection]=useState("home");
 useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setSection(e.target.id)}),{threshold:.45});document.querySelectorAll(".realm").forEach(el=>obs.observe(el));return()=>obs.disconnect()},[]);
 return <div className="kingdom">
  <nav className="nav" aria-label="Kingdom navigation"><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#education">Education</a><a href="#art">Art</a><a href="#resume">Resume</a><a href="#contact">Contact</a></nav>
  <div className="swan" aria-hidden="true" data-realm={section}/>
  <section id="home" className="realm hero"><div className="moon"/><div className="lake"/><div className="realm-inner"><p className="eyebrow">Enter the Kingdom</p><h1>Tahsin Nayeem Shrestha</h1><p className="identity">SOFTWARE ENGINEER · AI BUILDER · FOUNDER</p><p className="lede">I build systems that turn ambiguous information into useful structure — from LLM pipelines and data systems to interactive learning platforms and organizational intelligence.</p><p className="spell-note">Entrance spell controller next: camera OPEN ↔ CLOSE ×3 · pointer/touch CIRCLE ×3</p><div className="links"><a href="#experience">Follow the Swan ↓</a></div></div></section>
  <section id="experience" className="realm"><div className="realm-inner"><p className="eyebrow">The Swan's Journey · Experience</p><h2>Worlds that shaped how I build.</h2><p className="lede">The river moves through three engineering chapters: operations, machine learning, and production data systems.</p><div className="grid">{experiences.map(x=><article className="chapter" key={x.place}><p className="meta">{x.place}</p><h3>{x.role}</h3><p className="meta">{x.org}</p><p>{x.text}</p><div>{x.metrics.map(m=><span className="metric" key={m}>{m}</span>)}</div></article>)}</div></div></section>
  <section id="projects" className="realm"><div className="realm-inner"><p className="eyebrow">The Hall of Portals · Projects</p><h2>Worlds I built.</h2><p className="lede">Each portal represents a system with its own rules, architecture and reason for existing.</p><div className="grid">{projects.map(p=><article className="portal" key={p.title}>{p.status&&<span className="status">{p.status}</span>}<p className="meta">{p.sub}</p><h3>{p.title}</h3><p>{p.text}</p><div className="links">{p.demo&&<a href={p.demo} target="_blank" rel="noreferrer">Enter live system ↗</a>}{p.github&&<a href={p.github} target="_blank" rel="noreferrer">Source ↗</a>}</div></article>)}</div><p className="quote">Company Brain understands the company. AI Diet helps the company improve.</p></div></section>
  <section id="education" className="realm"><div className="realm-inner"><p className="eyebrow">The Library · Education</p><h2>The books behind the builder.</h2><div className="grid"><article className="book"><p className="meta">Stony Brook University · May 2026</p><h3>B.S. Information Systems</h3><p>College of Engineering and Applied Sciences. WISE Honors Program · Dean's List 2023 & 2025 · Global Excellence Scholarship.</p></article><article className="book"><p className="meta">Cornell University · May 2023–May 2024</p><h3>Machine Learning Foundations & Artificial Intelligence</h3><p>Certificate study spanning machine-learning foundations and applied AI.</p></article></div></div></section>
  <section id="art" className="realm"><div className="realm-inner"><p className="eyebrow">The Hidden Garden · Art</p><h2>Another way I study systems.</h2><p className="lede">Photography, drawing, mixed media and visual storytelling live beyond the engineering halls.</p><div className="art-window"><div><p className="eyebrow">Garden portal</p><h3>Art archive integration next</h3><p>Existing artwork data remains preserved while this portal is rebuilt around the kingdom.</p></div></div></div></section>
  <section id="resume" className="realm chronicle"><div className="realm-inner"><p className="eyebrow">The Chronicle · Resume</p><h2>The story, without the mythology.</h2><p className="lede">For recruiters and collaborators who want the concise record: engineering experience, projects, education and technical skills.</p><div className="links"><a href="/resume.pdf" target="_blank">Open Resume ↗</a><a href="/resume.pdf" download>Download PDF ↓</a></div></div></section>
  <section id="contact" className="realm"><div className="realm-inner"><p className="eyebrow">The Messenger Tower · Contact</p><h2>Send a message beyond the walls.</h2><p className="lede">For engineering roles, AI systems, product collaboration, or conversations about building unusual things.</p><div className="links"><a href="mailto:shrestha.official.1407@gmail.com">Email</a><a href="https://github.com/Tshrestha-1114" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/tahsin-nayeem-shrestha/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></section>
 </div>
}
